
submit:
	/home/opt/spark-2.4.7-bin-without-hadoop/bin/spark-submit \
	--class SimpleApp --master yarn --deploy-mode cluster \
	--driver-memory 4g  --executor-memory 2g --executor-cores 1  \
	--queue default ../target/scala-2.11/spark-learning_2.11-0.1.jar
